### ISSUE TITLE
Please switch to OID regitered under the Debian OID

### ISSUE THREAD

**Issue by JohnLines** [credativ/postfix-ldap-schema#2]
I have registered an OID for postfix-ldap-schema under the Debian OID. Switching to this will avoid the possibility of an OID clash if someone uses the same OpenLDAP experimental OIDs.

Note that the OID definition at http://oid-info.com/get/1.3.6.1.4.1.9586.100.8 (currently pending) points to my fork at present, but I would prefer to update it to point your this upstream

**Comment by dlucredativ** [comment]
Hi, thank you for your contribution. However I got the info that we will archive this repository.
